/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mux.Csharp.Sdk.Api;
using Mux.Csharp.Sdk.Model;
using Mux.Csharp.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mux.Csharp.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListFiltersResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListFiltersResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListFiltersResponseData
        //private ListFiltersResponseData instance;

        public ListFiltersResponseDataTests()
        {
            // TODO uncomment below to create an instance of ListFiltersResponseData
            //instance = new ListFiltersResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListFiltersResponseData
        /// </summary>
        [Fact]
        public void ListFiltersResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListFiltersResponseData
            //Assert.IsType<ListFiltersResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Basic'
        /// </summary>
        [Fact]
        public void BasicTest()
        {
            // TODO unit test for the property 'Basic'
        }
        /// <summary>
        /// Test the property 'Advanced'
        /// </summary>
        [Fact]
        public void AdvancedTest()
        {
            // TODO unit test for the property 'Advanced'
        }

    }

}
