/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mux.Csharp.Sdk.Api;
using Mux.Csharp.Sdk.Model;
using Mux.Csharp.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mux.Csharp.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListAllMetricValuesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListAllMetricValuesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListAllMetricValuesResponse
        //private ListAllMetricValuesResponse instance;

        public ListAllMetricValuesResponseTests()
        {
            // TODO uncomment below to create an instance of ListAllMetricValuesResponse
            //instance = new ListAllMetricValuesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListAllMetricValuesResponse
        /// </summary>
        [Fact]
        public void ListAllMetricValuesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListAllMetricValuesResponse
            //Assert.IsType<ListAllMetricValuesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'TotalRowCount'
        /// </summary>
        [Fact]
        public void TotalRowCountTest()
        {
            // TODO unit test for the property 'TotalRowCount'
        }
        /// <summary>
        /// Test the property 'Timeframe'
        /// </summary>
        [Fact]
        public void TimeframeTest()
        {
            // TODO unit test for the property 'Timeframe'
        }

    }

}
