/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mux.Csharp.Sdk.Api;
using Mux.Csharp.Sdk.Model;
using Mux.Csharp.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mux.Csharp.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LiveStreamStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LiveStreamStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LiveStreamStatus
        //private LiveStreamStatus instance;

        public LiveStreamStatusTests()
        {
            // TODO uncomment below to create an instance of LiveStreamStatus
            //instance = new LiveStreamStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LiveStreamStatus
        /// </summary>
        [Fact]
        public void LiveStreamStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" LiveStreamStatus
            //Assert.IsType<LiveStreamStatus>(instance);
        }



    }

}
