/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Mux.Csharp.Sdk.Api;
using Mux.Csharp.Sdk.Model;
using Mux.Csharp.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Mux.Csharp.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OverallValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverallValuesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OverallValues
        //private OverallValues instance;

        public OverallValuesTests()
        {
            // TODO uncomment below to create an instance of OverallValues
            //instance = new OverallValues();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OverallValues
        /// </summary>
        [Fact]
        public void OverallValuesInstanceTest()
        {
            // TODO uncomment below to test "IsType" OverallValues
            //Assert.IsType<OverallValues>(instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'TotalWatchTime'
        /// </summary>
        [Fact]
        public void TotalWatchTimeTest()
        {
            // TODO unit test for the property 'TotalWatchTime'
        }
        /// <summary>
        /// Test the property 'TotalViews'
        /// </summary>
        [Fact]
        public void TotalViewsTest()
        {
            // TODO unit test for the property 'TotalViews'
        }
        /// <summary>
        /// Test the property 'GlobalValue'
        /// </summary>
        [Fact]
        public void GlobalValueTest()
        {
            // TODO unit test for the property 'GlobalValue'
        }

    }

}
