/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Mux.Csharp.Sdk.Client;
using Mux.Csharp.Sdk.Api;
// uncomment below to import models
//using Mux.Csharp.Sdk.Model;

namespace Mux.Csharp.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing RealTimeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RealTimeApiTests : IDisposable
    {
        private RealTimeApi instance;

        public RealTimeApiTests()
        {
            instance = new RealTimeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RealTimeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RealTimeApi
            //Assert.IsType<RealTimeApi>(instance);
        }

        /// <summary>
        /// Test GetRealtimeBreakdown
        /// </summary>
        [Fact]
        public void GetRealtimeBreakdownTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string REALTIME_METRIC_ID = null;
            //string dimension = null;
            //decimal? timestamp = null;
            //List<string> filters = null;
            //string orderBy = null;
            //string orderDirection = null;
            //var response = instance.GetRealtimeBreakdown(REALTIME_METRIC_ID, dimension, timestamp, filters, orderBy, orderDirection);
            //Assert.IsType<GetRealTimeBreakdownResponse>(response);
        }

        /// <summary>
        /// Test GetRealtimeHistogramTimeseries
        /// </summary>
        [Fact]
        public void GetRealtimeHistogramTimeseriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string REALTIME_HISTOGRAM_METRIC_ID = null;
            //List<string> filters = null;
            //var response = instance.GetRealtimeHistogramTimeseries(REALTIME_HISTOGRAM_METRIC_ID, filters);
            //Assert.IsType<GetRealTimeHistogramTimeseriesResponse>(response);
        }

        /// <summary>
        /// Test GetRealtimeTimeseries
        /// </summary>
        [Fact]
        public void GetRealtimeTimeseriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string REALTIME_METRIC_ID = null;
            //List<string> filters = null;
            //var response = instance.GetRealtimeTimeseries(REALTIME_METRIC_ID, filters);
            //Assert.IsType<GetRealTimeTimeseriesResponse>(response);
        }

        /// <summary>
        /// Test ListRealtimeDimensions
        /// </summary>
        [Fact]
        public void ListRealtimeDimensionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListRealtimeDimensions();
            //Assert.IsType<ListRealTimeDimensionsResponse>(response);
        }

        /// <summary>
        /// Test ListRealtimeMetrics
        /// </summary>
        [Fact]
        public void ListRealtimeMetricsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListRealtimeMetrics();
            //Assert.IsType<ListRealTimeMetricsResponse>(response);
        }
    }
}
