/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mux.Csharp.Sdk.Client.OpenAPIDateConverter;

namespace Mux.Csharp.Sdk.Model
{
    /// <summary>
    /// Detailed state information about the asset ingest process.
    /// </summary>
    [DataContract(Name = "AssetProgress")]
    public partial class AssetProgress : IEquatable<AssetProgress>, IValidatableObject
    {
        /// <summary>
        /// The detailed state of the asset ingest process. This field is useful for relaying more granular processing information to end users when a [non-standard input is encountered](https://www.mux.com/docs/guides/minimize-processing-time#non-standard-input).  - &#x60;ingesting&#x60;: Asset is being ingested (initial processing before or after transcoding). While in this state, the &#x60;progress&#x60; percentage will be 0. - &#x60;transcoding&#x60;: Asset is undergoing non-standard transcoding. - &#x60;completed&#x60;: Asset processing is complete (&#x60;status&#x60; is &#x60;ready&#x60;). While in this state, the &#x60;progress&#x60; percentage will be 100. - &#x60;live&#x60;: Asset is a live stream currently in progress. While in this state, the &#x60;progress&#x60; percentage will be -1. - &#x60;errored&#x60;: Asset has encountered an error (&#x60;status&#x60; is &#x60;errored&#x60;). While in this state, the &#x60;progress&#x60; percentage will be -1. 
        /// </summary>
        /// <value>The detailed state of the asset ingest process. This field is useful for relaying more granular processing information to end users when a [non-standard input is encountered](https://www.mux.com/docs/guides/minimize-processing-time#non-standard-input).  - &#x60;ingesting&#x60;: Asset is being ingested (initial processing before or after transcoding). While in this state, the &#x60;progress&#x60; percentage will be 0. - &#x60;transcoding&#x60;: Asset is undergoing non-standard transcoding. - &#x60;completed&#x60;: Asset processing is complete (&#x60;status&#x60; is &#x60;ready&#x60;). While in this state, the &#x60;progress&#x60; percentage will be 100. - &#x60;live&#x60;: Asset is a live stream currently in progress. While in this state, the &#x60;progress&#x60; percentage will be -1. - &#x60;errored&#x60;: Asset has encountered an error (&#x60;status&#x60; is &#x60;errored&#x60;). While in this state, the &#x60;progress&#x60; percentage will be -1. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Ingesting for value: ingesting
            /// </summary>
            [EnumMember(Value = "ingesting")]
            Ingesting = 1,

            /// <summary>
            /// Enum Transcoding for value: transcoding
            /// </summary>
            [EnumMember(Value = "transcoding")]
            Transcoding = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Live for value: live
            /// </summary>
            [EnumMember(Value = "live")]
            Live = 4,

            /// <summary>
            /// Enum Errored for value: errored
            /// </summary>
            [EnumMember(Value = "errored")]
            Errored = 5

        }


        /// <summary>
        /// The detailed state of the asset ingest process. This field is useful for relaying more granular processing information to end users when a [non-standard input is encountered](https://www.mux.com/docs/guides/minimize-processing-time#non-standard-input).  - &#x60;ingesting&#x60;: Asset is being ingested (initial processing before or after transcoding). While in this state, the &#x60;progress&#x60; percentage will be 0. - &#x60;transcoding&#x60;: Asset is undergoing non-standard transcoding. - &#x60;completed&#x60;: Asset processing is complete (&#x60;status&#x60; is &#x60;ready&#x60;). While in this state, the &#x60;progress&#x60; percentage will be 100. - &#x60;live&#x60;: Asset is a live stream currently in progress. While in this state, the &#x60;progress&#x60; percentage will be -1. - &#x60;errored&#x60;: Asset has encountered an error (&#x60;status&#x60; is &#x60;errored&#x60;). While in this state, the &#x60;progress&#x60; percentage will be -1. 
        /// </summary>
        /// <value>The detailed state of the asset ingest process. This field is useful for relaying more granular processing information to end users when a [non-standard input is encountered](https://www.mux.com/docs/guides/minimize-processing-time#non-standard-input).  - &#x60;ingesting&#x60;: Asset is being ingested (initial processing before or after transcoding). While in this state, the &#x60;progress&#x60; percentage will be 0. - &#x60;transcoding&#x60;: Asset is undergoing non-standard transcoding. - &#x60;completed&#x60;: Asset processing is complete (&#x60;status&#x60; is &#x60;ready&#x60;). While in this state, the &#x60;progress&#x60; percentage will be 100. - &#x60;live&#x60;: Asset is a live stream currently in progress. While in this state, the &#x60;progress&#x60; percentage will be -1. - &#x60;errored&#x60;: Asset has encountered an error (&#x60;status&#x60; is &#x60;errored&#x60;). While in this state, the &#x60;progress&#x60; percentage will be -1. </value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetProgress" /> class.
        /// </summary>
        /// <param name="state">The detailed state of the asset ingest process. This field is useful for relaying more granular processing information to end users when a [non-standard input is encountered](https://www.mux.com/docs/guides/minimize-processing-time#non-standard-input).  - &#x60;ingesting&#x60;: Asset is being ingested (initial processing before or after transcoding). While in this state, the &#x60;progress&#x60; percentage will be 0. - &#x60;transcoding&#x60;: Asset is undergoing non-standard transcoding. - &#x60;completed&#x60;: Asset processing is complete (&#x60;status&#x60; is &#x60;ready&#x60;). While in this state, the &#x60;progress&#x60; percentage will be 100. - &#x60;live&#x60;: Asset is a live stream currently in progress. While in this state, the &#x60;progress&#x60; percentage will be -1. - &#x60;errored&#x60;: Asset has encountered an error (&#x60;status&#x60; is &#x60;errored&#x60;). While in this state, the &#x60;progress&#x60; percentage will be -1. .</param>
        /// <param name="progress">Represents the estimated completion percentage. Returns &#x60;0 - 100&#x60; when in &#x60;ingesting&#x60;, &#x60;transcoding&#x60;, or &#x60;completed&#x60; state, and &#x60;-1&#x60; when in &#x60;live&#x60; or &#x60;errored&#x60; state..</param>
        public AssetProgress(StateEnum? state = default(StateEnum?), double progress = default(double))
        {
            this.State = state;
            this.Progress = progress;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Represents the estimated completion percentage. Returns &#x60;0 - 100&#x60; when in &#x60;ingesting&#x60;, &#x60;transcoding&#x60;, or &#x60;completed&#x60; state, and &#x60;-1&#x60; when in &#x60;live&#x60; or &#x60;errored&#x60; state.
        /// </summary>
        /// <value>Represents the estimated completion percentage. Returns &#x60;0 - 100&#x60; when in &#x60;ingesting&#x60;, &#x60;transcoding&#x60;, or &#x60;completed&#x60; state, and &#x60;-1&#x60; when in &#x60;live&#x60; or &#x60;errored&#x60; state.</value>
        [DataMember(Name = "progress", EmitDefaultValue = false)]
        public double Progress { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetProgress {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Progress: ").Append(Progress).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetProgress);
        }

        /// <summary>
        /// Returns true if AssetProgress instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetProgress to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetProgress input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.Progress == input.Progress ||
                    this.Progress.Equals(input.Progress)
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                hashCode = (hashCode * 59) + this.Progress.GetHashCode();
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Progress (double) maximum
            if (this.Progress > (double)100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Progress, must be a value less than or equal to 100.", new [] { "Progress" });
            }

            // Progress (double) minimum
            if (this.Progress < (double)-1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Progress, must be a value greater than or equal to -1.", new [] { "Progress" });
            }

            yield break;
        }
    }

}
