/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mux.Csharp.Sdk.Client.OpenAPIDateConverter;

namespace Mux.Csharp.Sdk.Model
{
    /// <summary>
    /// AssetRecordingTimes
    /// </summary>
    [DataContract(Name = "Asset_recording_times")]
    public partial class AssetRecordingTimes : IEquatable<AssetRecordingTimes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetRecordingTimes" /> class.
        /// </summary>
        /// <param name="startedAt">The time at which the recording for the live stream started. The time value is Unix epoch time represented in ISO 8601 format..</param>
        /// <param name="duration">The duration of the live stream recorded. The time value is in seconds..</param>
        public AssetRecordingTimes(DateTime startedAt = default(DateTime), double duration = default(double))
        {
            this.StartedAt = startedAt;
            this.Duration = duration;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The time at which the recording for the live stream started. The time value is Unix epoch time represented in ISO 8601 format.
        /// </summary>
        /// <value>The time at which the recording for the live stream started. The time value is Unix epoch time represented in ISO 8601 format.</value>
        [DataMember(Name = "started_at", EmitDefaultValue = false)]
        public DateTime StartedAt { get; set; }

        /// <summary>
        /// The duration of the live stream recorded. The time value is in seconds.
        /// </summary>
        /// <value>The duration of the live stream recorded. The time value is in seconds.</value>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public double Duration { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetRecordingTimes {\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetRecordingTimes);
        }

        /// <summary>
        /// Returns true if AssetRecordingTimes instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetRecordingTimes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetRecordingTimes input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.StartedAt == input.StartedAt ||
                    (this.StartedAt != null &&
                    this.StartedAt.Equals(input.StartedAt))
                ) && 
                (
                    this.Duration == input.Duration ||
                    this.Duration.Equals(input.Duration)
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StartedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Duration.GetHashCode();
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
