/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mux.Csharp.Sdk.Client.OpenAPIDateConverter;

namespace Mux.Csharp.Sdk.Model
{
    /// <summary>
    /// InputFile
    /// </summary>
    [DataContract(Name = "InputFile")]
    public partial class InputFile : IEquatable<InputFile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InputFile" /> class.
        /// </summary>
        /// <param name="containerFormat">containerFormat.</param>
        /// <param name="tracks">tracks.</param>
        public InputFile(string containerFormat = default(string), List<InputTrack> tracks = default(List<InputTrack>))
        {
            this.ContainerFormat = containerFormat;
            this.Tracks = tracks;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets ContainerFormat
        /// </summary>
        [DataMember(Name = "container_format", EmitDefaultValue = false)]
        public string ContainerFormat { get; set; }

        /// <summary>
        /// Gets or Sets Tracks
        /// </summary>
        [DataMember(Name = "tracks", EmitDefaultValue = false)]
        public List<InputTrack> Tracks { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InputFile {\n");
            sb.Append("  ContainerFormat: ").Append(ContainerFormat).Append("\n");
            sb.Append("  Tracks: ").Append(Tracks).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InputFile);
        }

        /// <summary>
        /// Returns true if InputFile instances are equal
        /// </summary>
        /// <param name="input">Instance of InputFile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InputFile input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ContainerFormat == input.ContainerFormat ||
                    (this.ContainerFormat != null &&
                    this.ContainerFormat.Equals(input.ContainerFormat))
                ) && 
                (
                    this.Tracks == input.Tracks ||
                    this.Tracks != null &&
                    input.Tracks != null &&
                    this.Tracks.SequenceEqual(input.Tracks)
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContainerFormat != null)
                {
                    hashCode = (hashCode * 59) + this.ContainerFormat.GetHashCode();
                }
                if (this.Tracks != null)
                {
                    hashCode = (hashCode * 59) + this.Tracks.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
