/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mux.Csharp.Sdk.Client.OpenAPIDateConverter;

namespace Mux.Csharp.Sdk.Model
{
    /// <summary>
    /// UpdateLiveStreamGeneratedSubtitlesRequest
    /// </summary>
    [DataContract(Name = "UpdateLiveStreamGeneratedSubtitlesRequest")]
    public partial class UpdateLiveStreamGeneratedSubtitlesRequest : IEquatable<UpdateLiveStreamGeneratedSubtitlesRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateLiveStreamGeneratedSubtitlesRequest" /> class.
        /// </summary>
        /// <param name="generatedSubtitles">Update automated speech recognition subtitle configuration for a live stream. At most one subtitle track is allowed..</param>
        public UpdateLiveStreamGeneratedSubtitlesRequest(List<LiveStreamGeneratedSubtitleSettings> generatedSubtitles = default(List<LiveStreamGeneratedSubtitleSettings>))
        {
            this.GeneratedSubtitles = generatedSubtitles;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Update automated speech recognition subtitle configuration for a live stream. At most one subtitle track is allowed.
        /// </summary>
        /// <value>Update automated speech recognition subtitle configuration for a live stream. At most one subtitle track is allowed.</value>
        [DataMember(Name = "generated_subtitles", EmitDefaultValue = false)]
        public List<LiveStreamGeneratedSubtitleSettings> GeneratedSubtitles { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateLiveStreamGeneratedSubtitlesRequest {\n");
            sb.Append("  GeneratedSubtitles: ").Append(GeneratedSubtitles).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateLiveStreamGeneratedSubtitlesRequest);
        }

        /// <summary>
        /// Returns true if UpdateLiveStreamGeneratedSubtitlesRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateLiveStreamGeneratedSubtitlesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateLiveStreamGeneratedSubtitlesRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.GeneratedSubtitles == input.GeneratedSubtitles ||
                    this.GeneratedSubtitles != null &&
                    input.GeneratedSubtitles != null &&
                    this.GeneratedSubtitles.SequenceEqual(input.GeneratedSubtitles)
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GeneratedSubtitles != null)
                {
                    hashCode = (hashCode * 59) + this.GeneratedSubtitles.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
