/*
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * Contact: devex@mux.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Mux.Csharp.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Mux.Csharp.Sdk.Model
{
    /// <summary>
    /// UpdateReferrerDomainRestrictionRequest
    /// </summary>
    [JsonConverter(typeof(UpdateReferrerDomainRestrictionRequestJsonConverter))]
    [DataContract(Name = "UpdateReferrerDomainRestrictionRequest")]
    public partial class UpdateReferrerDomainRestrictionRequest : AbstractOpenAPISchema, IEquatable<UpdateReferrerDomainRestrictionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateReferrerDomainRestrictionRequest" /> class
        /// with the <see cref="ReferrerDomainRestriction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ReferrerDomainRestriction.</param>
        public UpdateReferrerDomainRestrictionRequest(ReferrerDomainRestriction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ReferrerDomainRestriction))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ReferrerDomainRestriction");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ReferrerDomainRestriction`. If the actual instance is not `ReferrerDomainRestriction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ReferrerDomainRestriction</returns>
        public ReferrerDomainRestriction GetReferrerDomainRestriction()
        {
            return (ReferrerDomainRestriction)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateReferrerDomainRestrictionRequest {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, UpdateReferrerDomainRestrictionRequest.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of UpdateReferrerDomainRestrictionRequest
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of UpdateReferrerDomainRestrictionRequest</returns>
        public static UpdateReferrerDomainRestrictionRequest FromJson(string jsonString)
        {
            UpdateReferrerDomainRestrictionRequest newUpdateReferrerDomainRestrictionRequest = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newUpdateReferrerDomainRestrictionRequest;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ReferrerDomainRestriction).GetProperty("AdditionalProperties") == null)
                {
                    newUpdateReferrerDomainRestrictionRequest = new UpdateReferrerDomainRestrictionRequest(JsonConvert.DeserializeObject<ReferrerDomainRestriction>(jsonString, UpdateReferrerDomainRestrictionRequest.SerializerSettings));
                }
                else
                {
                    newUpdateReferrerDomainRestrictionRequest = new UpdateReferrerDomainRestrictionRequest(JsonConvert.DeserializeObject<ReferrerDomainRestriction>(jsonString, UpdateReferrerDomainRestrictionRequest.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ReferrerDomainRestriction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ReferrerDomainRestriction: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newUpdateReferrerDomainRestrictionRequest;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateReferrerDomainRestrictionRequest);
        }

        /// <summary>
        /// Returns true if UpdateReferrerDomainRestrictionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateReferrerDomainRestrictionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateReferrerDomainRestrictionRequest input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for UpdateReferrerDomainRestrictionRequest
    /// </summary>
    public class UpdateReferrerDomainRestrictionRequestJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(UpdateReferrerDomainRestrictionRequest).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return UpdateReferrerDomainRestrictionRequest.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
